{
  "openapi": "3.0.3",
  "info": {
    "title": "Academy  - OpenAPI 3.0",
    "description": "API documentation for the Academy Website, providing endpoints to manage courses, students, and more\n\nSome useful links:\n- [BackEnd repository](https://github.com/Muhamadzulfikar/FSW-BE-Final-Project)\n- [ERD link](https://dbdiagram.io/d/655ed5293be14957878fc325)\n",
    "license": {
      "name": "ISC License",
      "url": "https://www.isc.org/licenses/"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://final-project-online-course.et.r.appspot.com/"
    }
  ],
  "tags": [
    {
      "name": "Root",
      "description": "Root end-point"
    },
    {
      "name": "Category",
      "description": "Everything about category management"
    },
    {
      "name": "Class",
      "description": "Everything about class management"
    },
    {
      "name": "Payment",
      "description": "Everything about payment"
    },
    {
      "name": "Auth",
      "description": "Everything about payment"
    }
  ],
  "paths": {
    "/": {
      "get": {
        "tags": [
          "Root"
        ],
        "summary": "Test your ping to the server here",
        "operationId": "testPing",
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ping"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/internalError"
                }
              }
            }
          }
        }
      }
    },
    "/v1/course-categories": {
      "get": {
        "tags": [
          "Category"
        ],
        "summary": "Find all Category",
        "description": "This end point will serve all list of categories",
        "operationId": "getAllCategories",
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/categories"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/internalError"
                }
              }
            }
          }
        }
      }
    },
    "/v1/courses": {
      "get": {
        "tags": [
          "Class"
        ],
        "summary": "Find all Class if there are no params or spesific class if there are params",
        "description": "This end point will serve all list of class",
        "operationId": "getAllClass",
        "parameters": [
          {
            "name": "categoryId",
            "in": "query",
            "description": "The category of the classes",
            "required": false,
            "schema": {
              "type": "string",
              "example": "1,3"
            }
          },
          {
            "name": "level",
            "in": "query",
            "description": "The level of the classes",
            "required": false,
            "schema": {
              "type": "string",
              "example": "beginner,intermediate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/classes"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/internalError"
                }
              }
            }
          }
        }
      }
    },
    "/v1/course/{id}": {
      "get": {
        "tags": [
          "Class"
        ],
        "summary": "Find detail class by ID",
        "description": "This end point will serve data of detailed class",
        "operationId": "getDetailClass",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of class to fetch",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/paramsID"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/classDetail"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/internalError"
                }
              }
            }
          }
        }
      }
    },
    "/v1/course-dashboard": {
      "get": {
        "tags": [
          "Class"
        ],
        "summary": "Get Dashboard Admin",
        "description": "This end point will serve data of user's classes",
        "operationId": "getAdminCourses",
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/userCoursePayments"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/internalError"
                }
              }
            }
          }
        }
      }
    },
    "/v1/course": {
      "get": {
        "tags": ["Class"],
        "summary": "Get Management Class Admin",
        "description": "This end point will serve data of classes",
        "operationId": "getCourse",
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/adminManagementClass"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/internalError"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Class"],
        "summary": "Create Class",
        "description": "This end point will create data of class",
        "operationId": "createAdminCourses",
        "requestBody": {
          "description": "Data of the course to be created",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/reqClass"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/reqClass"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/internalError"
                }
              }
            }
          }
        }
      }
    },
    "/v1/courses/{id}": {
      "put": {
        "tags": ["Class"],
        "summary": "Update Class",
        "description": "This end point will update data of class",
        "operationId": "updateAdminCourses",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of the course to be updated",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "description": "Data of the course to be updated",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/reqClass"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "example": {
                  "status": "OK",
                  "code": 200,
                  "message": "Success"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/internalError"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Class"],
        "summary": "Delete Class",
        "description": "This end point will delete data of class",
        "operationId": "deleteAdminCourses",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of the course to be updated",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "description": "Data of the course to be deleted",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/reqClass"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "example": {
                  "status": "OK",
                  "code": 200,
                  "message": "Success"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/internalError"
                }
              }
            }
          }
        }
      }
    },
    "/v1/buy-course": {
      "post": {
        "tags": ["Payment"],
        "summary": "Make Payment",
        "description": "This end point will post data to UserCourse",
        "operationId": "buyCourse",
        "requestBody": {
          "description": "Data of the course to be updated",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/reqBuyCourse"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Created"
                    },
                    "code": {
                      "type": "number",
                      "example": 201
                    },
                    "message": {
                      "type": "string",
                      "example": "Success"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/resBuyCourse"
                      }
                    }
                  }
                },
                "example": {
                  "status": "Created",
                  "code": 201,
                  "message": "Success",
                  "data": [
                    {
                      "expiredAt": "2023-12-13 14:54:26.057+07",
                      "uuid": "7b835907-c7b4-43ed-a9ba-cf7e6d7043cb",
                      "user_course_uuid": "7b835907-c7b4-43ed-a9ba-cf7e6d7043cb",
                      "payment_method": "credit card",
                      "is_paid": false
                    }
                  ]
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/internalError"
                }
              }
            }
          }
        }
      }
    },
    "/v1/payment": {
      "put": {
        "tags": ["Payment"],
        "summary": "Make Payment",
        "description": "This endpoint will update data in UserCoursePayment",
        "operationId": "payment",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of userClass to fetch",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/paramsID"
            }
          }
        ],
        "requestBody": {
          "description": "Data of the userCoursePayment to be updated",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/reqPayment"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/resPayment"
                },
                "example": {
                  "status": "Created",
                  "code": 201,
                  "message": "Success"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/internalError"
                }
              }
            }
          }
        }
      }
    },
    "/v1/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "Login",
        "description": "This endpoint will login a user",
        "operationId": "login",
        "requestBody": {
          "description": "Data of the userCoursePayment to be updated",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/reqLogin"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/resLogin"
                },
                "example": {
                  "status": "Created",
                  "code": 201,
                  "message": "Success",
                  "data": [
                    {
                      "name": "Fahrel",
                      "email": "fahrel@gmail.com",
                      "phone": "081231238",
                      "country": "Indonesia",
                      "city": "Jember",
                      "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYxMGY2ZWQwLTEzYzAtNDYzZC05MWRhLWYwNmVmM2I5MjhlZSIsImlhdCI6MTcwMjQ2MzEyNSwiZXhwIjoxNzAyNDY0OTI1fQ.r94ceYn_zj1O8g7KuNUpc9lZxzU04m26s8wQsdSck88"
                    }
                  ]
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/internalError"
                }
              }
            }
          }
        }
      }
    },
    "/v1/register": {
      "post": {
        "tags": ["Auth"],
        "summary": "Register",
        "description": "This endpoint will register a user",
        "operationId": "register",
        "requestBody": {
          "description": "post a data to user",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/reqRegister"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "example": {
                  "status": "Created",
                  "code": 201,
                  "message": "Success",
                  "data": [
                    {
                      "name": "Fahrel",
                      "email": "fahrel@gmail.com",
                      "phone": "081231238",
                      "country": null,
                      "city": null,
                      "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYxMGY2ZWQwLTEzYzAtNDYzZC05MWRhLWYwNmVmM2I5MjhlZSIsImlhdCI6MTcwMjQ2MzEyNSwiZXhwIjoxNzAyNDY0OTI1fQ.r94ceYn_zj1O8g7KuNUpc9lZxzU04m26s8wQsdSck88"
                    }
                  ]
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/internalError"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "paramsID": {
        "type": "string",
        "format": "uuid",
        "example": "b74507f3-ec93-4d10-a62f-9d20479a3f56"
      },
      "ping": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "example": "OK"
          },
          "code": {
            "type": "number",
            "example": 200
          },
          "message": {
            "type": "string",
            "example": "Ping succesfully"
          }
        }
      },
      "resLogin": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Fahrel"
          },
          "email": {
            "type": "string",
            "example": "fahrel@gmail.com"
          },
          "phone": {
            "type": "string",
            "example": "081231238"
          },
          "country": {
            "type": "string",
            "example": "Indonesia"
          },
          "city": {
            "type": "string",
            "example": "Jember"
          },
          "token": {
            "type": "string",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYxMGY2ZWQwLTEzYzAtNDYzZC05MWRhLWYwNmVmM2I5MjhlZSIsImlhdCI6MTcwMjQ2MzEyNSwiZXhwIjoxNzAyNDY0OTI1fQ.r94ceYn_zj1O8g7KuNUpc9lZxzU04m26s8wQsdSck88"
          }
        }
      },
      "category": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid",
            "example": "0033d087-4a4c-4828-a987-e6e0c72d37e9"
          },
          "name": {
            "type": "string",
            "example": "UI/UX Design"
          },
          "image": {
            "type": "string",
            "example": "https://www.image.com"
          }
        }
      },
      "categories": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "example": "OK"
          },
          "code": {
            "type": "number",
            "example": 200
          },
          "message": {
            "type": "string",
            "example": "Success"
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/category"
            }
          }
        }
      },
      "modul": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "example": "title"
          },
          "link": {
            "type": "string",
            "example": "https://youtube.com"
          }
        }
      },
      "user": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "1",
            "example": "1"
          },
          "uuid": {
            "type": "string",
            "format": "uuid",
            "example": "0033d087-4a4c-4828-a987-e6e0c72d37e9"
          },
          "name":{
            "type":"string",
            "example": "John Doe"
          },
          "email":{
            "type":"string",
            "example":"JohnDoe@gmail.com"
          },
          "password":{
            "type":"string",
            "example":"$2b$10$6K5cZJrUfI2w6u1Qq2nQ6eQ3DZ5Y6rZQ8Qp9XbXv5wZaLqZ7kZcX."
          },
          "phone":{
            "type":"string",
            "example":"0812349271"
          },
          "country":{
            "type":"string",
            "example":"Indonesia"
          },
          "city":{
            "type":"string",
            "example":"Jakarta"
          },
          "role":{
            "type":"string",
            "example":"admin"
          }
        }
      },
      "classModule": {
        "type": "object",
        "properties": {
          "chapter": {
            "type": "string",
            "example": "chapter 1 - Pendahuluan"
          },
          "estimation": {
            "type": "number",
            "example": 60
          },
          "module": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/modul"
            }
          }
        }
      },
      "userClass": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "1",
            "example": "1"
          },
          "uuid": {
            "type": "string",
            "format": "uuid",
            "example": "0033d087-4a4c-4828-a987-e6e0c72d37e9"
          },
          "user_uuid": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/user"
            }
          },
          "class":{
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/class"
            }
          },
          "is_onboarding":{
            "type":"boolean",
            "example":true
          }
        }
      },
      "classID": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "example": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"
          },
          "classTarget": {
            "type": "array",
            "items": {
              "type": "string",
              "example": [
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
              ]
            }
          },
          "telegram": {
            "type": "string",
            "example": "telegram.co.id"
          },
          "onboarding": {
            "type": "string",
            "example": "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
          },
          "classModule": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/classModule"
            }
          }
        }
      },
      "userCoursePayments": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "1",
            "example": "1"
          },
          "uuid": {
            "type": "string",
            "format": "uuid",
            "example": "0033d087-4a4c-4828-a987-e6e0c72d37e9"
          },
          "user_class_uuid": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/userClass"
            }
          },
          "payment_method": {
            "type": "string",
            "example": "credit card"
          },
          "is_paid": {
            "type": "boolean",
            "example": true
          }
        }
      },

      "class": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid",
            "example": "0033d087-4a4c-4828-a987-e6e0c72d37e9"
          },
          "name": {
            "type": "string",
            "example": "Intro to Basic of User Interaction Design"
          },
          "image": {
            "type": "string",
            "example": "https://www.image.com"
          },
          "author": {
            "type": "string",
            "example": "nameexample"
          },
          "price": {
            "type": "number",
            "example": 280000
          },
          "level": {
            "type": "string",
            "example": "Advanced"
          },
          "rating": {
            "type": "number",
            "example": 4.9
          },
          "totalModule": {
            "type": "number",
            "example": 5
          },
          "totalMinute": {
            "type": "number",
            "example": 60
          },
          "isPremium": {
            "type": "boolean",
            "example": true
          },
          "classCode": {
            "type": "string",
            "example": "UIUX0123"
          },
          "category": {
            "type": "string",
            "example": "UI/UX Design"
          }
        }
      },
      "classDetailNew": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid",
            "example": "0033d087-4a4c-4828-a987-e6e0c72d37e9"
          },
          "name": {
            "type": "string",
            "example": "Intro to Basic of User Interaction Design"
          },
          "image": {
            "type": "string",
            "example": "https://www.image.com"
          },
          "author": {
            "type": "string",
            "example": "nameexample"
          },
          "price": {
            "type": "number",
            "example": 280000
          },
          "level": {
            "type": "string",
            "example": "Advanced"
          },
          "rating": {
            "type": "number",
            "example": 4.9
          },
          "totalModule": {
            "type": "number",
            "example": 5
          },
          "totalMinute": {
            "type": "number",
            "example": 60
          },
          "isPremium": {
            "type": "boolean",
            "example": true
          },
          "classCode": {
            "type": "string",
            "example": "UIUX0123"
          },
          "category": {
            "type": "string",
            "example": "UI/UX Design"
          }
        }
      },
      "adminManagementClass": {
        "type": "object",
        "properties": {
          "classCode": {
            "type": "string",
            "example": "UIUX0123"
          },
          "category": {
            "type": "string",
            "example": "UI/UX Design"
          },
          "name": {
            "type": "string",
            "example": "Intro to Basic of User Interaction Design"
          },
          "isPremium": {
            "type": "boolean",
            "example": true
          },
          "level": {
            "type": "string",
            "example": "Advanced"
          },
          "price": {
            "type": "number",
            "example": 280000
          }
        }
      },
      "classDetail": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "example": "OK"
          },
          "code": {
            "type": "number",
            "example": 200
          },
          "message": {
            "type": "string",
            "example": "Success"
          },
          "data": {
            "allOf": [
              {
                "$ref": "#/components/schemas/class"
              },
              {
                "$ref": "#/components/schemas/classID"
              }
            ]
          }
        }
      },
      "adminClass": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "example": "OK"
          },
          "code": {
            "type": "number",
            "example": 200
          },
          "message": {
            "type": "string",
            "example": "Success"
          },
          "data": {
            "allOf": [
              {
                "$ref": "#/components/schemas/class"
              },
              {
                "$ref": "#/components/schemas/classID"
              }
            ]
          }
        }
      },
      "classes": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "example": "OK"
          },
          "code": {
            "type": "number",
            "example": 200
          },
          "message": {
            "type": "string",
            "example": "Success"
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/class"
            }
          }
        }
      },
      "reqClass": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Intro to Basic of User Interaction Design"
          },
          "image": {
            "type": "string",
            "example": "https://www.image.com"
          },
          "author": {
            "type": "string",
            "example": "nameexample"
          },
          "price": {
            "type": "number",
            "example": 280000
          },
          "level": {
            "type": "string",
            "example": "Advanced"
          },
          "rating": {
            "type": "number",
            "example": 4.9
          },
          "totalModule": {
            "type": "number",
            "example": 5
          },
          "totalMinute": {
            "type": "number",
            "example": 60
          },
          "isPremium": {
            "type": "boolean",
            "example": true
          },
          "classCode": {
            "type": "string",
            "example": "UIUX0123"
          },
          "category": {
            "type": "string",
            "example": "UI/UX Design"
          }
        }
      },
      "reqPayment": {
        "type": "object",
        "properties": {
          "payment_method": {
            "type": "string",
            "example": "credit card"
          },
          "is_paid": {
            "type": "boolean",
            "example": true
          }
        }
      },
      "reqRegister": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Fahrel"
          },
          "email": {
            "type": "string",
            "example": "fahrel@gmail.com"
          },
          "password": {
            "type": "string",
            "example": "fahrel123"
          },
          "phone": {
            "type": "string",
            "example": "081231237"
          }
        }
      },
      "reqLogin": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "example": "fahrel@gmail.com"
          },
          "password": {
            "type": "string",
            "example": "fahrel123"
          }
        }
      },
      "reqBuyCourse": {
        "type": "object",
        "properties": {
          "course_uuid": {
            "type": "string",
            "example": "7b835907-c7b4-43ed-a9ba-cf7e6d7043cb"
          },
          "is_onboarding": {
            "type": "boolean",
            "example": true
          }
        }
      },
      "resBuyCourse": {
        "type": "object",
        "properties": {
          "expiredAt": {
            "type": "string",
            "example": "2023-12-13 14:54:26.057+07"
          },
          "uuid": {
            "type": "string",
            "example": "7b835907-c7b4-43ed-a9ba-cf7e6d7043cb"
          },
          "user_course_uuid": {
            "type": "string",
            "example": "7b835907-c7b4-43ed-a9ba-cf7e6d7043cb"
          },
          "payment_method": {
            "type": "string",
            "example": "credit card"
          },
          "is_paid": {
            "type": "boolean",
            "example": false
          }
        }
      },
      "unauthorized": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "example": "FAILED"
          },
          "code": {
            "type": "number",
            "example": 401
          },
          "message": {
            "type": "string",
            "example": "Please login first"
          }
        }
      },
      "internalError": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "example": "FAILED"
          },
          "code": {
            "type": "number",
            "example": 500
          },
          "error": {
            "type": "string",
            "example": "Internal Server Error"
          }
        }
      }
    }
  }
}